### ISSUE TITLE
googlechrome/simplehttp2server 3.1.3 fixes a compile bug

### ISSUE THREAD

**Issue by diligiant** [1000ch/simplehttp2server#4]
I initially created a pull request but I don't feel comfortable releasing someone else binaries (`vendor/`) ; speaking of which, I was wondering why you don't simply grab them from the original repo?

I could pull that if you wish.

```
https://github.com/GoogleChrome/simplehttp2server/releases/download/3.1.3/
simplehttp2server_darwin_amd64
simplehttp2server_linux_386
simplehttp2server_linux_amd64
simplehttp2server_linux_arm
simplehttp2server_windows_amd64.exe
```

**Comment by 1000ch** [comment]
Fixed on #3 🙌
